service_name: github

status:
  project:
    default:
      threshold: 0.01
  patch:
    default:
      threshold: 0.01
  flags:
    baseline:
      threshold: 0.01
    unit-mpi:
      threshold: 0.01
    unit-ngv:
      threshold: 0.01
    unit:
      threshold: 0.01
