@startuml packages_neurodamus
set namespaceSeparator none
package "neurodamus" as neurodamus {
}
package "neurodamus.cell_distributor" as neurodamus.cell_distributor {
}
package "neurodamus.commands" as neurodamus.commands {
}
package "neurodamus.connection" as neurodamus.connection {
}
package "neurodamus.connection_manager" as neurodamus.connection_manager {
}
package "neurodamus.core" as neurodamus.core {
}
package "neurodamus.core._engine" as neurodamus.core._engine {
}
package "neurodamus.core._mpi" as neurodamus.core._mpi {
}
package "neurodamus.core._neurodamus" as neurodamus.core._neurodamus {
}
package "neurodamus.core._neuron" as neurodamus.core._neuron {
}
package "neurodamus.core._shmutils" as neurodamus.core._shmutils {
}
package "neurodamus.core._utils" as neurodamus.core._utils {
}
package "neurodamus.core.cell" as neurodamus.core.cell {
}
package "neurodamus.core.configuration" as neurodamus.core.configuration {
}
package "neurodamus.core.coreneuron_configuration" as neurodamus.core.coreneuron_configuration {
}
package "neurodamus.core.mechanisms" as neurodamus.core.mechanisms {
}
package "neurodamus.core.nodeset" as neurodamus.core.nodeset {
}
package "neurodamus.core.random" as neurodamus.core.random {
}
package "neurodamus.core.stimuli" as neurodamus.core.stimuli {
}
package "neurodamus.core.synapses" as neurodamus.core.synapses {
}
package "neurodamus.gap_junction" as neurodamus.gap_junction {
}
package "neurodamus.gj_user_corrections" as neurodamus.gj_user_corrections {
}
package "neurodamus.hocify" as neurodamus.hocify {
}
package "neurodamus.io" as neurodamus.io {
}
package "neurodamus.io.cell_readers" as neurodamus.io.cell_readers {
}
package "neurodamus.io.sonata_config" as neurodamus.io.sonata_config {
}
package "neurodamus.io.synapse_reader" as neurodamus.io.synapse_reader {
}
package "neurodamus.lfp_manager" as neurodamus.lfp_manager {
}
package "neurodamus.metype" as neurodamus.metype {
}
package "neurodamus.modification_manager" as neurodamus.modification_manager {
}
package "neurodamus.morphio_wrapper" as neurodamus.morphio_wrapper {
}
package "neurodamus.neuromodulation_manager" as neurodamus.neuromodulation_manager {
}
package "neurodamus.ngv" as neurodamus.ngv {
}
package "neurodamus.node" as neurodamus.node {
}
package "neurodamus.replay" as neurodamus.replay {
}
package "neurodamus.report" as neurodamus.report {
}
package "neurodamus.stimulus_manager" as neurodamus.stimulus_manager {
}
package "neurodamus.target_manager" as neurodamus.target_manager {
}
package "neurodamus.utils" as neurodamus.utils {
}
package "neurodamus.utils.cli" as neurodamus.utils.cli {
}
package "neurodamus.utils.compat" as neurodamus.utils.compat {
}
package "neurodamus.utils.logging" as neurodamus.utils.logging {
}
package "neurodamus.utils.memory" as neurodamus.utils.memory {
}
package "neurodamus.utils.multimap" as neurodamus.utils.multimap {
}
package "neurodamus.utils.progressbar" as neurodamus.utils.progressbar {
}
package "neurodamus.utils.pyutils" as neurodamus.utils.pyutils {
}
package "neurodamus.utils.timeit" as neurodamus.utils.timeit {
}
neurodamus --> neurodamus.node
neurodamus.cell_distributor --> neurodamus.connection_manager
neurodamus.cell_distributor --> neurodamus.core
neurodamus.cell_distributor --> neurodamus.core.configuration
neurodamus.cell_distributor --> neurodamus.core.nodeset
neurodamus.cell_distributor --> neurodamus.io
neurodamus.cell_distributor --> neurodamus.io.cell_readers
neurodamus.cell_distributor --> neurodamus.lfp_manager
neurodamus.cell_distributor --> neurodamus.metype
neurodamus.cell_distributor --> neurodamus.target_manager
neurodamus.cell_distributor --> neurodamus.utils
neurodamus.cell_distributor --> neurodamus.utils.compat
neurodamus.cell_distributor --> neurodamus.utils.logging
neurodamus.cell_distributor --> neurodamus.utils.memory
neurodamus.commands --> neurodamus.core
neurodamus.commands --> neurodamus.core.configuration
neurodamus.commands --> neurodamus.hocify
neurodamus.commands --> neurodamus.utils.pyutils
neurodamus.commands --> neurodamus.utils.timeit
neurodamus.connection --> neurodamus.core
neurodamus.connection --> neurodamus.core.configuration
neurodamus.connection --> neurodamus.utils
neurodamus.connection --> neurodamus.utils.compat
neurodamus.connection --> neurodamus.utils.logging
neurodamus.connection --> neurodamus.utils.pyutils
neurodamus.connection_manager --> neurodamus.connection
neurodamus.connection_manager --> neurodamus.core
neurodamus.connection_manager --> neurodamus.core.configuration
neurodamus.connection_manager --> neurodamus.io.sonata_config
neurodamus.connection_manager --> neurodamus.io.synapse_reader
neurodamus.connection_manager --> neurodamus.target_manager
neurodamus.connection_manager --> neurodamus.utils
neurodamus.connection_manager --> neurodamus.utils.compat
neurodamus.connection_manager --> neurodamus.utils.logging
neurodamus.connection_manager --> neurodamus.utils.memory
neurodamus.connection_manager --> neurodamus.utils.pyutils
neurodamus.connection_manager --> neurodamus.utils.timeit
neurodamus.core --> neurodamus.core._engine
neurodamus.core --> neurodamus.core._mpi
neurodamus.core --> neurodamus.core._neurodamus
neurodamus.core --> neurodamus.core._neuron
neurodamus.core --> neurodamus.core._utils
neurodamus.core --> neurodamus.core.cell
neurodamus.core --> neurodamus.core.stimuli
neurodamus.core._mpi --> neurodamus.core._neuron
neurodamus.core._neurodamus --> neurodamus.core._engine
neurodamus.core._neurodamus --> neurodamus.core._mpi
neurodamus.core._neurodamus --> neurodamus.core._neuron
neurodamus.core._neurodamus --> neurodamus.core.configuration
neurodamus.core._neuron --> neurodamus.core.configuration
neurodamus.core._utils --> neurodamus.core._mpi
neurodamus.core.cell --> neurodamus.core.configuration
neurodamus.core.cell --> neurodamus.core.mechanisms
neurodamus.core.cell --> neurodamus.core.synapses
neurodamus.core.cell --> neurodamus.morphio_wrapper
neurodamus.core.configuration --> neurodamus.core._neurodamus
neurodamus.core.configuration --> neurodamus.core._shmutils
neurodamus.core.coreneuron_configuration --> neurodamus.core._utils
neurodamus.core.coreneuron_configuration --> neurodamus.core.configuration
neurodamus.core.mechanisms --> neurodamus.core._neuron
neurodamus.core.stimuli --> neurodamus.core.random
neurodamus.gap_junction --> neurodamus.connection_manager
neurodamus.gap_junction --> neurodamus.core.configuration
neurodamus.gap_junction --> neurodamus.gj_user_corrections
neurodamus.gap_junction --> neurodamus.io.sonata_config
neurodamus.gap_junction --> neurodamus.io.synapse_reader
neurodamus.gap_junction --> neurodamus.utils
neurodamus.gap_junction --> neurodamus.utils.compat
neurodamus.gap_junction --> neurodamus.utils.logging
neurodamus.gj_user_corrections --> neurodamus.core
neurodamus.gj_user_corrections --> neurodamus.core.configuration
neurodamus.hocify --> neurodamus.core
neurodamus.hocify --> neurodamus.utils.logging
neurodamus.hocify --> neurodamus.utils.progressbar
neurodamus.lfp_manager --> neurodamus.core
neurodamus.lfp_manager --> neurodamus.core.configuration
neurodamus.metype --> neurodamus.core
neurodamus.metype --> neurodamus.core.configuration
neurodamus.modification_manager --> neurodamus.core
neurodamus.modification_manager --> neurodamus.core.configuration
neurodamus.modification_manager --> neurodamus.utils.logging
neurodamus.neuromodulation_manager --> neurodamus.connection
neurodamus.neuromodulation_manager --> neurodamus.connection_manager
neurodamus.neuromodulation_manager --> neurodamus.core.configuration
neurodamus.neuromodulation_manager --> neurodamus.io.sonata_config
neurodamus.neuromodulation_manager --> neurodamus.io.synapse_reader
neurodamus.neuromodulation_manager --> neurodamus.utils.logging
neurodamus.ngv --> neurodamus.cell_distributor
neurodamus.ngv --> neurodamus.connection
neurodamus.ngv --> neurodamus.connection_manager
neurodamus.ngv --> neurodamus.core
neurodamus.ngv --> neurodamus.core.configuration
neurodamus.ngv --> neurodamus.io.sonata_config
neurodamus.ngv --> neurodamus.io.synapse_reader
neurodamus.ngv --> neurodamus.metype
neurodamus.ngv --> neurodamus.morphio_wrapper
neurodamus.ngv --> neurodamus.utils
neurodamus.ngv --> neurodamus.utils.logging
neurodamus.ngv --> neurodamus.utils.pyutils
neurodamus.node --> neurodamus.cell_distributor
neurodamus.node --> neurodamus.connection_manager
neurodamus.node --> neurodamus.core
neurodamus.node --> neurodamus.core._engine
neurodamus.node --> neurodamus.core._shmutils
neurodamus.node --> neurodamus.core.configuration
neurodamus.node --> neurodamus.core.coreneuron_configuration
neurodamus.node --> neurodamus.core.nodeset
neurodamus.node --> neurodamus.gap_junction
neurodamus.node --> neurodamus.io.sonata_config
neurodamus.node --> neurodamus.modification_manager
neurodamus.node --> neurodamus.neuromodulation_manager
neurodamus.node --> neurodamus.replay
neurodamus.node --> neurodamus.report
neurodamus.node --> neurodamus.stimulus_manager
neurodamus.node --> neurodamus.target_manager
neurodamus.node --> neurodamus.utils
neurodamus.node --> neurodamus.utils.compat
neurodamus.node --> neurodamus.utils.logging
neurodamus.node --> neurodamus.utils.memory
neurodamus.node --> neurodamus.utils.timeit
neurodamus.replay --> neurodamus.utils.logging
neurodamus.replay --> neurodamus.utils.multimap
neurodamus.replay --> neurodamus.utils.timeit
neurodamus.report --> neurodamus.core
neurodamus.stimulus_manager --> neurodamus.core
neurodamus.stimulus_manager --> neurodamus.core.configuration
neurodamus.stimulus_manager --> neurodamus.core.random
neurodamus.stimulus_manager --> neurodamus.core.stimuli
neurodamus.stimulus_manager --> neurodamus.utils.logging
neurodamus.target_manager --> neurodamus.core
neurodamus.target_manager --> neurodamus.core.configuration
neurodamus.target_manager --> neurodamus.core.nodeset
neurodamus.target_manager --> neurodamus.utils
neurodamus.target_manager --> neurodamus.utils.compat
neurodamus.target_manager --> neurodamus.utils.logging
neurodamus.utils --> neurodamus.utils.pyutils
neurodamus.utils.logging --> neurodamus.utils.pyutils
neurodamus.utils.memory --> neurodamus.utils.compat
neurodamus.utils.memory --> neurodamus.utils.logging
neurodamus.utils.memory --> neurodamus.utils.logging
neurodamus.utils.multimap --> neurodamus.utils.compat
neurodamus.utils.timeit --> neurodamus.utils.logging
neurodamus.utils.timeit --> neurodamus.utils.logging
@enduml
