name: Lint Check

on: [pull_request, push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v6

    - name: Install tox
      run: pip install tox

    - name: Run linting
      run: tox -elint
