name: Lint Check

on: [pull_request, push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        persist-credentials: false
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6

    - name: Install tox
      run: pip install tox

    - name: Run linting
      run: tox -elint
