name: Run unit tests

on:
    pull_request:
    push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox

    - name: Run tox
      run: |
        tox -eunit
