name: Run unit tests

on:
    pull_request:
    push:
      branches:
        - master

jobs:
  baseline-coverage:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox coverage

    - name: Run tox
      run: |
        tox -ebaseline

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        flag-name: baseline

  unit-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox coverage

    - name: Run tox
      run: |
        tox -eunit

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        flag-name: unit
